from .AccDistIndex import ADIAgent
from .Aroon import AroonAgent
from .AverageDirectionalIndex import ADXAgent
from .AwesomeOscillator import AwesomeOscillatorAgent
from .BollingerChannelPercantageBand import BCPBAgent
from .ChaikinMoneyFlow import CHFAgent
from .CommodityChannelIndex import CCIAgent
from .DetrendPriceOscillator import DPOAgent
from .DonchianChannel import DonchianChannelAgent
from .EaseOfMovement import EMVAgent
from .ForceIndex import ForceIndexAgent
from .IchimokuClouds import ICAgent
from .KAMA import KAMAAgent
from .KeltnerChannel import KeltnerChannelAgent
from .KST import KSTAgent
from .MassIndex import MIAgent
from .MFI import MFIAgent
from .MovingAverage import MACAgent
from .PercentagePriceOscillator import PPOAgent
from .PercentageVolumeOscillator import PVOAgent
from .PSAR import PSARAgent
from .RateOfChange import ROCAgent
from .RelativeStrengthIndex import RSIAgent
from .STC import STCAgent
from .Stochastic import StochasticAgent
from .StochasticRSI import StochasticRSIAgent
# from .Trend import TrendAgent # Makes problems in the implementation
from .TRIX import TRIXAgent
from .TSI import TSIAgent
from .UlcerIndex import UlcerIndexAgent
from .UltimateOscillator import UltimateOscillatorAgent
from .Volume import VolumeAgent
from .VolumePriceTrend import VolumePriceTrendAgent
from .Vortex import VortexAgent
from .WilliamsRIndicator import WilliamRAgent